name: Example workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Download Encoder
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: 'https://code.aliyun.com/qhduan/zh-roberta-wwm/raw/2c0d7fd709e4719a9ab2ca297f51b24e20586dbe/zh-roberta-wwm-L1.tar.gz'
        file-name: 'zh-roberta-wwm-L1.tar.gz'
        location: './'
    - name: Download Bert
      run: |
        mkdir -p encoders/zh-roberta-wwm-L1
        tar xvf zh-roberta-wwm-L1.tar.gz -C encoders/zh-roberta-wwm-L1
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest tfnlu/tests/ --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true